#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Sat Feb 11 13:55:42 2017

@author: il
"""
p=[]
def flatten(aList):
    
    for i in aList:
       if type(i) is list:
          flatten(i)
       else:
           p.append(i)
    return p
    
           
   
aList=[[1,'a',['cat'],2],[[[3]],'dog'],4,5]
print(flatten(aList))